name: List Folders on Push

on:
  push:

jobs:
  list-folders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show branch name
        run: |
         echo "Current branch: ${{ github.ref_name }}"

      - name: List all folders in the repo
        run: |
          echo "All folders in this branch:"
          find . -type d | sed 's|^\./||' | sort
